/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreensNameRouteImport } from './routes/screens/$name'
import { Route as FlowsNameRouteImport } from './routes/flows/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensNameRoute = ScreensNameRouteImport.update({
  id: '/screens/$name',
  path: '/screens/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsNameRoute = FlowsNameRouteImport.update({
  id: '/flows/$name',
  path: '/flows/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flows/$name': typeof FlowsNameRoute
  '/screens/$name': typeof ScreensNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flows/$name': typeof FlowsNameRoute
  '/screens/$name': typeof ScreensNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flows/$name': typeof FlowsNameRoute
  '/screens/$name': typeof ScreensNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flows/$name' | '/screens/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flows/$name' | '/screens/$name'
  id: '__root__' | '/' | '/flows/$name' | '/screens/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsNameRoute: typeof FlowsNameRoute
  ScreensNameRoute: typeof ScreensNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens/$name': {
      id: '/screens/$name'
      path: '/screens/$name'
      fullPath: '/screens/$name'
      preLoaderRoute: typeof ScreensNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$name': {
      id: '/flows/$name'
      path: '/flows/$name'
      fullPath: '/flows/$name'
      preLoaderRoute: typeof FlowsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsNameRoute: FlowsNameRoute,
  ScreensNameRoute: ScreensNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
